env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb
  - prettier
#parser:
parserOptions:
  ecmaVersion: 12
plugins:
  - prettier
rules:
  prettier/prettier:
    - 1
    - singleQuote: true
  no-unused-vars: 1
  camelcase: 1
  func-names: 0
  no-use-before-define: 0
  no-shadow: 0
  no-restricted-globals: 1
  no-nested-ternary: 1
  no-underscore-dangle: 1
  no-plusplus: ['error', { 'allowForLoopAfterthoughts': true }]
  no-param-reassign: ['error', { 'props': false }]
